### PR TITLE
Modified readme file

### PR DESCRIPTION
**Pull request by luqmanmusah**
Merging development branch to master branch to deploy on heroku.

### CODE REVIEW

**Review by Temmarie — COMMENTED** [review]
## Changes Required! :recycle:

### Hi @luqmanmusah and @Addis0943    ! :wave: :wave:

#### Good job getting to the end of the final rails project in this module!! You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**
- [x] Link to Heroku in README file is added ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/heroku.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).
- [x] The link to the deployed app is working



__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by luqmanmusah** [comment]
Added the live link to my readme file and it is working.
Thank you

**Review by umairarshadbutt — COMMENTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @luqmanmusah and @Addis0943 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] Please work on suggested changes by the previous code reviewer. I have explored your repository that you uploaded the Live link in the `master` branch. please update the readme file of the `development` branch. 


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by luqmanmusah** [comment]
I have updated the development branch to include the live link in the readme file

**Review by mricanho — COMMENTED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @Addis0943 @luqmanmusah, good job on your deployment! 🔥 

boomeasy


Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

**Pull request merged**
